### 데이터 실수화

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
X_train = pd.DataFrame(['남성','여성','남성','여성','남성','여성'], columns=['성별'])
X_train

성별
0  남성
1  여성
2  남성
3  여성
4  남성
5  여성

In [4]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   성별      6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes


In [5]:
X_train['성별'].value_counts()

남성    3
여성    3
Name: 성별, dtype: int64

In [6]:
encoing = LabelEncoder()
encoing.fit(X_train['성별'])
X_train['성별_인코딩'] = encoing.transform(X_train['성별'])
X_train

성별  성별_인코딩
0  남성       0
1  여성       1
2  남성       0
3  여성       1
4  남성       0
5  여성       1

In [7]:
print(list(encoing.classes_))
print(list(encoing.inverse_transform([1,0]))) # 숫자를 문자로 매핑(찾기)

['남성', '여성']
['여성', '남성']


In [8]:
X_train.head(2)

성별  성별_인코딩
0  남성       0
1  여성       1

In [9]:
one_encoding = OneHotEncoder(sparse=False)

one_encoding.fit(X_train[['성별']])
one_encoding.transform(X_train[['성별']])
print(one_encoding.get_feature_names())


['x0_남성' 'x0_여성']


C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [10]:
x_train_one = pd.DataFrame(one_encoding.transform(X_train[['성별']]), columns=['성별0','성별1'])
x_train_one

성별0  성별1
0  1.0  0.0
1  0.0  1.0
2  1.0  0.0
3  0.0  1.0
4  1.0  0.0
5  0.0  1.0

In [11]:
X_train = pd.concat([X_train,x_train_one], axis = 1)
X_train

성별  성별_인코딩  성별0  성별1
0  남성       0  1.0  0.0
1  여성       1  0.0  1.0
2  남성       0  1.0  0.0
3  여성       1  0.0  1.0
4  남성       0  1.0  0.0
5  여성       1  0.0  1.0

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
corpus = [
    '청년 인재 개발 양성 과정',
    '인공지능 청년 양성',
    '미래 인공지능 데이터 대한민국',
    '데이터 원유 기술사 청년 개발'
]
corpus

['청년 인재 개발 양성 과정', '인공지능 청년 양성', '미래 인공지능 데이터 대한민국', '데이터 원유 기술사 청년 개발']

In [14]:
type(corpus)

list

In [15]:
count_vect = CountVectorizer()
count_vect.fit(corpus)
count_vect.vocabulary_

{'청년': 10,
 '인재': 9,
 '개발': 0,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2}

In [16]:
print(count_vect.transform(corpus).toarray())
features = count_vect.transform(corpus)
features

[[1 1 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 1 1 1 0 0 1 0 0]
 [1 0 1 0 1 0 0 1 0 0 1]]


<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [17]:
vocab = count_vect.get_feature_names()
vocab

C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '청년']

In [18]:
DTM = pd.DataFrame(features.toarray(), columns= vocab).head()
DTM

개발  과정  기술사  대한민국  데이터  미래  양성  원유  인공지능  인재  청년
0   1   1    0     0    0   0   1   0     0   1   1
1   0   0    0     0    0   0   1   0     1   0   1
2   0   0    0     1    1   1   0   0     1   0   0
3   1   0    1     0    1   0   0   1     0   0   1

In [19]:
count_vect.transform(['기술사 대한민국 인재 만세']).toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
corpus

['청년 인재 개발 양성 과정', '인공지능 청년 양성', '미래 인공지능 데이터 대한민국', '데이터 원유 기술사 청년 개발']

In [22]:
tfid = TfidfVectorizer()
tfid.fit(corpus)
tfid.vocabulary_

{'청년': 10,
 '인재': 9,
 '개발': 0,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2}

In [23]:
tfid.transform(corpus).toarray()

array([[0.41263976, 0.52338122, 0.        , 0.        , 0.        ,
        0.        , 0.41263976, 0.        , 0.        , 0.52338122,
        0.33406745],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.61366674, 0.        , 0.61366674, 0.        ,
        0.49681612],
       [0.        , 0.        , 0.        , 0.55528266, 0.43779123,
        0.55528266, 0.        , 0.        , 0.43779123, 0.        ,
        0.        ],
       [0.41263976, 0.        , 0.52338122, 0.        , 0.41263976,
        0.        , 0.        , 0.52338122, 0.        , 0.        ,
        0.33406745]])

In [24]:
features_idf = tfid.transform(corpus)
features_idf

<4x11 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [25]:
vocab_idf = count_vect.get_feature_names()
vocab_idf

C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '청년']

In [26]:
DTM_idf = pd.DataFrame(features_idf.toarray(), columns= vocab_idf)
DTM_idf

개발        과정       기술사      대한민국       데이터        미래        양성  \
0  0.41264  0.523381  0.000000  0.000000  0.000000  0.000000  0.412640   
1  0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.613667   
2  0.00000  0.000000  0.000000  0.555283  0.437791  0.555283  0.000000   
3  0.41264  0.000000  0.523381  0.000000  0.412640  0.000000  0.000000   

         원유      인공지능        인재        청년  
0  0.000000  0.000000  0.523381  0.334067  
1  0.000000  0.613667  0.000000  0.496816  
2  0.000000  0.437791  0.000000  0.000000  
3  0.523381  0.000000  0.000000  0.334067